import { Icons } from "@/components";

export const perks = [
    {
        icon: Icons.auth,
        title: "Sign Up",
        info: "Create your free account to get started with Assignmate.",
    },
    {
        icon: Icons.customize,
        title: "Customize",
        info: "Choose a service and customize it to fit your needs.",
    },
    {
        icon: Icons.launch,
        title: "Delivery",
        info: "Get it delivered to you within deadline.",
    },
];

export const features = [
    {
        icon: Icons.bolt,
        title: "Fast Delivery",
        info: "Get your assignments in minutes with our fast and reliable delivery service.",
    },
    {
        icon: Icons.palette,
        title: "Customizable Assignments",
        info: "We provide a variety of customizable assignments to suit your needs.",
    },
    {
        icon: Icons.seo,
        title: "No AI Assignments ",
        info: "Our team of experts will work to deliver the best results for you and us.",
    },
    {
        icon: Icons.monitor,
        title: "Available 24/7",
        info: "We are available 24/7 to answer any questions you may have.",
    },
    {
        icon: Icons.shop,
        title: "Delivering Assignments Since 2014",
        info: "Started small in quarantine Grew into a major company.",
    },
    {
        icon: Icons.server,
        title: "Secure Assignments and Privacy",
        info: "Enjoy peace of mind with our secure services Your information remains confidential.",
    },
];

export const pricingCards = [
    {
        title: "Starter",
        description: "Perfect for trying our services.",
        price: "$25",
        duration: "1 Assignment",
        highlight: "Key features",
        buttonText: "Buy",
        features: ["4 days deadline", "1 Team member","1 Page max", "Basic features"],
        priceId: "",
    },
    {
        title: "Kit",
        description: "The ultimate Assignment kit.",
        price: "$50",
        duration: "3 assignment kit",
        highlight: "Key features",
        buttonText: "Buy",
        features: ["2 day deadline", "5 Team members", "Customizable", "Support and updates"],
        priceId: "price_1OYxkqFj9oKEERu1KfJGWxgN",
    },
    {
        title: "Urgent",
        description: "The 11:59pm Submission.",
        price: "$100",
        duration: "month",
        highlight: "Everything in Starter, plus",
        buttonText: "Buy",
        features: ["Quick Submission", "Multiple Team members", "Customizable", "Priority support (24/7)"],
        priceId: "price_1OYxkqFj9oKEERu1NbKUxXxN",
    },
];

export const bentoCards = [
    {
        title: 'Start with Inspiration',
        info: 'Browse our vast library of pre-designed templates or upload your own images.',
        imgSrc: '/assets/bento-1.svg', // Lightbulb or Inspiration icon
        alt: 'Inspiration for website creation'
    },
    {
        title: 'AI Assists Your Vision',
        info: 'Our intelligent AI tailors suggestions and functionalities based on your goals.',
        imgSrc: '/assets/bento1.svg', // AI Assistant icon
        alt: 'AI website building assistant'
    },
    {
        title: 'Drag & Drop Customization',
        info: 'Effortlessly personalize your website with our intuitive drag-and-drop editor.',
        imgSrc: '/assets/bento1.svg', // Drag and Drop icon or hand editing a website
        alt: 'Website customization with drag and drop'
    },
    {
        title: 'Launch & Shine Online',
        info: 'Publish your website with a single click and take your brand to the world.',
        imgSrc: '/assets/bento1.svg', // Rocket launching or website going live
        alt: 'Website launch and publication'
    },
];

export const reviews = [
    {
        name: "Emily R.",
        username: "University Student",
        body: "Work is 100% hand written not generated by AI. I vouch.",
    },
    {
        name: "Sarah Patel",
        username: "University Student",
        body: "Their attention to detail is impressive!, Assignments are delivered on time.",
    },
    {
        name: "David Lee",
        username: "College Freshman",
        body: "I was skeptical at first, but the essay I received was top notch!.",
    },
    {
        name: "Michael Kim",
        username: "University Student",
        body: "Their writers truly understood the prompts and delivered original work.",
    },
    {
        name: "Rachel Brown",
        username: "College Freshman",
        body: "Excellent essays and assignments that earned me good grades. ",
    },
    {
        name: "Kevin Chen",
        username: "University Student",
        body: "Not only do they deliver quality work, but their customer service is fast.",
    },
];
